### ISSUE TITLE
==> gitlabci: ruby2.1: No such file or directory -- ruby2.1-dev (LoadError)

### ISSUE THREAD

**Issue by louis813** [tuminoid/gitlabci-installer#2]
Hi man,

I was used OS X 10.10.3, and the virtual box to build a gitlab ci environment, everything goes well except that I met "==> gitlabci: ruby2.1: No such file or directory -- ruby2.1-dev (LoadError)" when I ran **vagrant provision**.

Then I checked the file "/tmp/vagrant-shell", and found there is a blank line between the install command: 
The origin **install-gitlab-ci.sh**
```
apt-get -y install curl build-essential checkinstall openssh-server git postfix redis-server logrotate \
  ruby2.1 ruby2.1-dev ruby1.9.1-dev nodejs
```

The vagrant file **/tmp/vagrant-shell**
```
apt-get -y install curl build-essential checkinstall openssh-server git postfix redis-server logrotate \
 
 ruby2.1 ruby2.1-dev ruby1.9.1-dev nodejs
```

When I remove the "\" in the  install-gitlab-ci.sh, the vagrant provision was succeed :smile:

**Comment by tuminoid** [comment]
I have no idea why Virtualbox would translate backslash into a new line when transfering files for provisioning, but I've put the command in one line now.

Fixed in #304365a.
